# Generated by Django 6.0 on 2025-12-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensordata",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="audio/"),
        ),
    ]
