# Generated by Django 6.0 on 2025-12-28 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device_api", "0002_sensordata_audio_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sensordata",
            name="humidity",
        ),
        migrations.RemoveField(
            model_name="sensordata",
            name="temperature",
        ),
    ]
